#!/usr/bin/env bash
# install-safe-shims.sh — installs a PATH-shim layer that gates npm/pnpm/yarn/npx
# installs through socket.dev and/or a 7-day-age policy.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/sburl/CrossCheck/main/scripts/install-safe-shims.sh | bash
#   # or after cloning CrossCheck:
#   bash scripts/install-safe-shims.sh
#
# Environment overrides:
#   REAL_NPM=/path/to/npm      force a specific npm binary
#   PREFIX=~/bin               where to put the shim dir (default: ~/bin)
#   NO_NPM_CONFIG=1            skip `npm config set ignore-scripts true`
#   NO_RC_APPEND=1             skip touching ~/.zshrc / ~/.bashrc / ~/.profile
#   INSTALL_AGE_DAYS=10        default min-age for npm-safe-install (default: 7)
#
# Idempotent — safe to re-run. Will not pick up a previously-installed shim
# as REAL_NPM (the most common foot-gun, since the shim ends up earlier in PATH).

set -eu

PREFIX="${PREFIX:-$HOME/bin}"
SHIM_DIR="$PREFIX/safe-shims"
SHIM="$SHIM_DIR/npm"
SAFE_INSTALL="$PREFIX/npm-safe-install"
INSTALL_AGE_DAYS="${INSTALL_AGE_DAYS:-7}"

mkdir -p "$SHIM_DIR" "$PREFIX"

# ---------------------------------------------------------------------------
# 1. Find the real npm — never resolve to anything inside safe-shims/
# ---------------------------------------------------------------------------
find_real_npm() {
    if [ -n "${REAL_NPM:-}" ]; then
        case "$REAL_NPM" in *safe-shims*) REAL_NPM="";; esac
        if [ -n "${REAL_NPM:-}" ] && [ -x "$REAL_NPM" ]; then
            echo "$REAL_NPM"; return 0
        fi
    fi
    # Prefer explicit known paths first
    for cand in \
        /opt/homebrew/bin/npm \
        /usr/local/bin/npm \
        /usr/bin/npm; do
        case "$cand" in *safe-shims*) continue ;; esac
        [ -x "$cand" ] && echo "$cand" && return 0
    done
    # Fallback: PATH search with safe-shims filtered out
    local clean_path
    clean_path=$(echo "${PATH:-}" | tr ':' '\n' | grep -v safe-shims | paste -sd: -)
    PATH="$clean_path" command -v npm 2>/dev/null
}

REAL_NPM=$(find_real_npm || true)
if [ -z "${REAL_NPM:-}" ]; then
    cat >&2 <<'MSG'
❌ No npm binary found.

Install Node first:
  macOS:  brew install node
  Linux:  https://nodejs.org/  (or your distro's node package)

Then re-run this installer.
MSG
    exit 1
fi
echo "→ real npm: $REAL_NPM"

# ---------------------------------------------------------------------------
# 2. Write the shim
# ---------------------------------------------------------------------------
REAL_NPX=$(dirname "$REAL_NPM")/npx
[ -x "$REAL_NPX" ] || REAL_NPX="$(PATH=$(echo "${PATH:-}" | tr ':' '\n' | grep -v safe-shims | paste -sd: -) command -v npx 2>/dev/null || echo "")"

cat > "$SHIM" <<SHIM_END
#!/usr/bin/env bash
# Supply-chain shim for npm / npx / pnpm / yarn (symlinked).
# Detects \$0 and routes to the matching real binary.
# Generated by CrossCheck install-safe-shims.sh
# Bypass per-call:  SAFE_INSTALL_OVERRIDE=1 <tool> <args>
# Source: https://github.com/sburl/CrossCheck

set -u

REAL_NPM="__REAL_NPM__"
REAL_NPX="__REAL_NPX__"
REAL_PNPM="\$(command -v pnpm 2>/dev/null | grep -v safe-shims | head -1)"
REAL_YARN="\$(command -v yarn 2>/dev/null | grep -v safe-shims | head -1)"

INVOKED_AS="\$(basename "\$0")"

block_msg() {
    cat >&2 <<MSG
🛡️  Supply-chain shim: \$INVOKED_AS \$* blocked.

  Use one of:
    socket \$INVOKED_AS \$*           # if socket CLI is installed (recommended)
    npm-safe-install <pkg>          # for npm install only, picks ≥7d-old version
    npm ci                          # lockfile-only restore (always safe)
    SAFE_INSTALL_OVERRIDE=1 \$INVOKED_AS \$*   # one-shot bypass

  Policy: https://github.com/sburl/CrossCheck/blob/main/docs/rules/trust-model.md
MSG
}

gate_through_socket() {
    local real="\$1"; shift
    if [ "\${SAFE_INSTALL_OVERRIDE:-0}" = "1" ]; then
        exec "\$real" "\$@"
    fi
    if command -v socket >/dev/null 2>&1; then
        case "\$INVOKED_AS" in
            npm) exec socket npm "\$@" ;;
            npx) exec socket npx "\$@" ;;
        esac
    fi
    block_msg "\$@"
    exit 1
}

case "\$INVOKED_AS" in
    npm)
        case "\${1:-}" in
            install|i|add|create|exec)
                for arg in "\$@"; do
                    case "\$arg" in
                        --offline|--prefer-offline) exec "\$REAL_NPM" "\$@" ;;
                    esac
                done
                gate_through_socket "\$REAL_NPM" "\$@"
                ;;
            *) exec "\$REAL_NPM" "\$@" ;;
        esac
        ;;
    npx)
        # Every npx is install-and-execute — gate by default.
        # Allow --no-install / --offline (only uses local node_modules / cache).
        for arg in "\$@"; do
            case "\$arg" in
                --no-install|--offline|--prefer-offline) exec "\$REAL_NPX" "\$@" ;;
            esac
        done
        gate_through_socket "\$REAL_NPX" "\$@"
        ;;
    pnpm)
        [ -z "\$REAL_PNPM" ] && { echo "pnpm not installed" >&2; exit 1; }
        case "\${1:-}" in
            add|install|dlx|create)
                if [ "\${SAFE_INSTALL_OVERRIDE:-0}" = "1" ]; then
                    exec "\$REAL_PNPM" "\$@"
                fi
                for arg in "\$@"; do
                    case "\$arg" in
                        --offline|--frozen-lockfile) exec "\$REAL_PNPM" "\$@" ;;
                    esac
                done
                block_msg "\$@"
                exit 1
                ;;
            *) exec "\$REAL_PNPM" "\$@" ;;
        esac
        ;;
    yarn)
        [ -z "\$REAL_YARN" ] && { echo "yarn not installed" >&2; exit 1; }
        case "\${1:-}" in
            add|create|dlx)
                if [ "\${SAFE_INSTALL_OVERRIDE:-0}" = "1" ]; then
                    exec "\$REAL_YARN" "\$@"
                fi
                for arg in "\$@"; do
                    case "\$arg" in
                        --offline|--frozen-lockfile) exec "\$REAL_YARN" "\$@" ;;
                    esac
                done
                block_msg "\$@"
                exit 1
                ;;
            *) exec "\$REAL_YARN" "\$@" ;;
        esac
        ;;
    *)
        exec "\$REAL_NPM" "\$@"
        ;;
esac
SHIM_END

# Replace placeholders with actual paths.
sed -e "s|__REAL_NPM__|$REAL_NPM|g" -e "s|__REAL_NPX__|$REAL_NPX|g" "$SHIM" > "$SHIM.new" && mv "$SHIM.new" "$SHIM"
chmod +x "$SHIM"

# ---------------------------------------------------------------------------
# 3. Write npm-safe-install (the 7-day-age installer)
# ---------------------------------------------------------------------------
cat > "$SAFE_INSTALL" <<SAFE_END
#!/usr/bin/env bash
# npm-safe-install <pkg> [<pkg>...] [-g] [--age-days N] [--dry-run]
#
# Installs each package at the newest version released >= AGE_DAYS days ago.
# Bypasses the npm shim by calling the real npm directly.

set -eu

REAL_NPM="__REAL_NPM__"

AGE_DAYS=__AGE_DAYS__
GLOBAL=""
DRYRUN=0
PKGS=()

while [ \$# -gt 0 ]; do
    case "\$1" in
        -g|--global)    GLOBAL="-g"; shift ;;
        --age-days)     AGE_DAYS="\$2"; shift 2 ;;
        --age-days=*)   AGE_DAYS="\${1#--age-days=}"; shift ;;
        --dry-run)      DRYRUN=1; shift ;;
        --)             shift; while [ \$# -gt 0 ]; do PKGS+=("\$1"); shift; done ;;
        -*)             echo "unknown flag: \$1" >&2; exit 1 ;;
        *)              PKGS+=("\$1"); shift ;;
    esac
done

[ \${#PKGS[@]} -eq 0 ] && {
    echo "usage: npm-safe-install <pkg> [...] [-g] [--age-days N] [--dry-run]" >&2
    exit 1
}

if ! command -v jq >/dev/null 2>&1; then
    echo "❌ npm-safe-install needs 'jq'. Install: brew install jq  (or apt/yum/dnf install jq)" >&2
    exit 1
fi

# Compute cutoff timestamp. Handle macOS (BSD date) and Linux (GNU date).
if date -u -v-1d +%s >/dev/null 2>&1; then
    cutoff_iso=\$(date -u -v-\${AGE_DAYS}d +%Y-%m-%dT%H:%M:%S.000Z)
else
    cutoff_iso=\$(date -u -d "\${AGE_DAYS} days ago" +%Y-%m-%dT%H:%M:%S.000Z)
fi

resolved=()
for raw in "\${PKGS[@]}"; do
    pkg="\${raw%@*}"; [ -z "\$pkg" ] && pkg="\$raw"
    echo "→ resolving \$pkg (need version released before \$cutoff_iso)..." >&2
    v=\$("\$REAL_NPM" view "\$pkg" time --json 2>/dev/null \\
        | jq -r --arg c "\$cutoff_iso" 'to_entries
            | map(select(.key | test("^[0-9]")))
            | map(select(.value < \$c))
            | map(select(.key | test("-") | not))
            | sort_by(.value) | last.key // empty')
    if [ -z "\$v" ]; then
        echo "  ⚠️  no version of \$pkg released >=\${AGE_DAYS}d ago — refusing" >&2
        exit 1
    fi
    t=\$("\$REAL_NPM" view "\$pkg" "time.\$v" 2>/dev/null || echo "unknown")
    echo "  ✓ \$pkg@\$v (released \$t)" >&2
    resolved+=("\$pkg@\$v")
done

if [ "\$DRYRUN" = "1" ]; then
    printf '%s\n' "\${resolved[@]}"
    exit 0
fi

SAFE_INSTALL_OVERRIDE=1 exec "\$REAL_NPM" install \$GLOBAL "\${resolved[@]}"
SAFE_END

sed -e "s|__REAL_NPM__|$REAL_NPM|g" -e "s|__AGE_DAYS__|$INSTALL_AGE_DAYS|g" "$SAFE_INSTALL" > "$SAFE_INSTALL.new" && mv "$SAFE_INSTALL.new" "$SAFE_INSTALL"
chmod +x "$SAFE_INSTALL"
echo "→ npm-safe-install default min-age: $INSTALL_AGE_DAYS days"

# ---------------------------------------------------------------------------
# 4. Symlinks for npx / pnpm / yarn
# ---------------------------------------------------------------------------
ln -sf "$SHIM" "$SHIM_DIR/npx"
ln -sf "$SHIM" "$SHIM_DIR/pnpm"
ln -sf "$SHIM" "$SHIM_DIR/yarn"

# ---------------------------------------------------------------------------
# 5. PATH wiring — append to whichever rc file exists; create one if none.
# ---------------------------------------------------------------------------
if [ "${NO_RC_APPEND:-0}" != "1" ]; then
    LINE='export PATH="$HOME/bin/safe-shims:$HOME/bin:$PATH"'
    appended=0
    for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
        if [ -f "$rc" ] && ! grep -q "safe-shims" "$rc" 2>/dev/null; then
            printf '\n# CrossCheck supply-chain shim — must come last to win PATH priority\n%s\n' "$LINE" >> "$rc"
            echo "→ appended PATH to $rc"
            appended=1
        fi
    done
    if [ "$appended" = "0" ] && ! grep -q "safe-shims" "$HOME/.zshrc" 2>/dev/null && ! grep -q "safe-shims" "$HOME/.bashrc" 2>/dev/null; then
        # No rc files existed and shim isn't already mentioned — create .zshrc
        # since that's the macOS / modern Linux default. Bash users will need
        # to manually add the line to .bashrc.
        printf '# CrossCheck supply-chain shim\n%s\n' "$LINE" >> "$HOME/.zshrc"
        echo "→ created $HOME/.zshrc with PATH export"
    fi
fi

# ---------------------------------------------------------------------------
# 6. Defang postinstall by default (the biggest single risk reduction).
# ---------------------------------------------------------------------------
if [ "${NO_NPM_CONFIG:-0}" != "1" ]; then
    "$REAL_NPM" config set ignore-scripts true
    echo "→ npm config ignore-scripts = $("$REAL_NPM" config get ignore-scripts)"
fi

# ---------------------------------------------------------------------------
# 7. Smoke test
# ---------------------------------------------------------------------------
echo
echo "=== smoke test ==="
PATH="$SHIM_DIR:$PREFIX:$PATH" which npm
echo "version (pass-through):"
PATH="$SHIM_DIR:$PREFIX:$PATH" "$SHIM" --version || true
echo "block test (expect policy message + rc=1, or socket banner if installed):"
set +e
PATH="$SHIM_DIR:$PREFIX:$PATH" "$SHIM" install --dry-run --no-save left-pad 2>&1 | head -8
rc=$?
set -e
echo "rc=$rc"

cat <<DONE

✅ Install complete.

Activate in current shell:
  source ~/.zshrc        # or ~/.bashrc, whichever the installer touched

For the agent layer (Claude Code PreToolUse hook + ask rules), see CrossCheck:
  https://github.com/sburl/CrossCheck

For the optional socket.dev malware scanner (recommended):
  brew install socket-cli           # macOS, if available
  npm-safe-install -g socket        # any platform — uses the shim's 7-day policy
  socket login

Per-call bypass:
  SAFE_INSTALL_OVERRIDE=1 npm install <pkg>

Per-project opt-back-in to postinstall scripts:
  echo "ignore-scripts=false" >> .npmrc

DONE
